name: Pipeline
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_PORT: '3333'
      APP_WEB_URL: 'http://localhost:3000'
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION_TIME: '7d'
      MAIL_HOST: 'smtp.test.io'
      MAIL_PORT: '587'
      MAIL_USER: 'test'
      MAIL_PASSWORD: 'password'
      DOCS_URL: 'https://github.com/DiegoVictor/proffy-api#errors-reference'
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '19.6'
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          npm ci
          npm run test
      - uses: codecov/codecov-action@v3
        with:
          directory: ./tests/coverage/
